CREATE DATABASE QUANLYTHUVIEN
GO
USE QUANLYTHUVIEN
GO
CREATE TABLE NHANVIEN (
	MaNV NVARCHAR(7)  NOT NULL,
	TenNV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT NVARCHAR(10) NOT NULL,
    MatKhau NVARCHAR(10) NOT NULL,
	GIOITINH BIT NOT NULL ,
	EMAIL NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(225),
	VAITRO BIT NOT NULL,
	PRIMARY KEY (MaNV)
)
GO
CREATE TABLE DOCGIA (
	MaDG NVARCHAR(5) NOT NULL,
	TenDG NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(10) NOT NULL,
	LOP NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL ,
	GIOITINH BIT NOT NULL,
	MaNV NVARCHAR(7) Not null,
	PRIMARY KEY (MaDG),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNv)
)
GO
CREATE TABLE SACH (
	MaSACH NVARCHAR(5) NOT NULL,
	TenSACH NVARCHAR(50) NOT NULL,
	TacGIA NVARCHAR(50) NOT NULL,
	NXB NVARCHAR(50) NOT NULL,
	THELOAI NVARCHAR(50)  NOT NULL ,
	MOTA NVARCHAR(225) NOT NULL,
	PRIMARY KEY (MaSACH)

)
GO
CREATE TABLE PHIEUMUON (
	MaPM NVARCHAR(5)NOT NULL,
	NGAYTAO DATE NOT NULL,
	NGAYTRA DATE NOT NULL,
	TRANGTHAI BIT NOT NULL,
	MaNV NVARCHAR(7) NOT NULL ,
	MaDG NVARCHAR(5) NOT NULL,
	GHICHU NVARCHAR(225),
	MaSACH NVARCHAR(5) NOT NULL,
	PRIMARY KEY(MaPM),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNv),
	FOREIGN KEY (MaDG) REFERENCES DOCGIA(MaDG),
	FOREIGN KEY (MaSACH) REFERENCES SACH(MaSACH)

)
GO
---DỮ LIỆU NHANVIEN
INSERT NhanVien (MaNV, TenNV, NGAYSINH, SDT, GIOITINH,MatKhau, EMAIL,GHICHU,VAITRO) 
VALUES (N'BaoNT',N'Nguyễn Thái Bảo','2004-05-22','0341647583','0',N'bao123', N'baont@gmail.com','', 1)
INSERT NhanVien (MaNV, TenNV, NGAYSINH, SDT, GIOITINH,MatKhau, EMAIL,GHICHU,VAITRO) 
VALUES (N'HieuHT',N'Huỳnh Thanh Hiếu','2004-09-10','0342657483','0',N'hieu321', N'hieuht@gmail.com','', 0)
INSERT NhanVien (MaNV, TenNV, NGAYSINH, SDT, GIOITINH,MatKhau, EMAIL,GHICHU,VAITRO) 
VALUES (N'DuyVN',N'Võ Nhựt Duy','2004-04-07','0345674893','0',N'duy456', N'duyvn@gmail.com','', 1)
INSERT NhanVien (MaNV, TenNV, NGAYSINH, SDT, GIOITINH,MatKhau, EMAIL,GHICHU,VAITRO) 
VALUES (N'MyTY',N'Trần Y Mỹ','2004-04-13','0347956743','1',N'my654', N'myty@gmail.com','', 0)
GO
SELECT* FROM NHANVIEN
---DỮ LIỆU DOCGIA
INSERT DOCGIA(MaDG, TenDG, NGAYSINH, SDT, GIOITINH,LOP, MaNV) 
VALUES (N'BAO01',N'Trần Văn Bảo','2003-08-10','0341675485','1',N'Lớp 12',N'HieuHT')
INSERT DOCGIA(MaDG, TenDG, NGAYSINH, SDT, GIOITINH,LOP, MaNV) 
VALUES (N'HNT02',N'Nguyễn Thị Huyền','2005-10-22','0342675485','1',N'Lớp 11A',N'BaoNT')
INSERT DOCGIA(MaDG, TenDG, NGAYSINH, SDT, GIOITINH,LOP, MaNV) 
VALUES (N'TTTH3',N'Trần Thị Huỳnh Trang','2003-09-23','0342567486','0',N'Lớp 12C',N'HieuHT')
INSERT DOCGIA(MaDG, TenDG, NGAYSINH, SDT, GIOITINH,LOP, MaNV) 
VALUES (N'LNV04',N'Nguyễn Văn Lành','2003-03-31','0342345467','1',N'Lớp 10A',N'DuyVN')
INSERT DOCGIA(MaDG, TenDG, NGAYSINH, SDT, GIOITINH,LOP, MaNV) 
VALUES (N'HHC05',N'Huỳnh Công Hiếu','2002-01-21','0341675485','0',N'Lớp 10B',N'MyTY')
SELECT* FROM DOCGIA
GO
INSERT SACH(MaSACH, TenSACH,TacGIA,NXB, THELOAI, MOTA) 
VALUES (N'MKNS1',N'Muôn Kiếp Nhân Sinh',N'Nguyên Phong',N'NXB Tổng Hợp TPHCM',N'Self help','')
INSERT SACH(MaSACH, TenSACH,TacGIA,NXB, THELOAI, MOTA) 
VALUES (N'TL1',N'Tĩnh Lặng',N'Thích Nhất Hạnh',N'NXB Thế giới',N'Self help','')
SELECT* FROM SACH
GO